### PR TITLE
fix usage of process builder

### PR DESCRIPTION
**Pull request by mythsman**

### CODE REVIEW

**Comment by mythsman** [comment]
#369

**Comment by rom1v** [comment]
Following the discussion on #369, this should be sufficient, isn't it?

Diff ignoring spaces (`git diff -b`):
```diff
diff --git a/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java b/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
index 03b6efc..7430560 100644
--- a/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
+++ b/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
@@ -357,10 +357,7 @@ public final class Main {
         List<String> command = createAdbCommand(serial, "shell", "dumpsys", "package", "com.genymobile.gnirehtet");
         Log.d(TAG, "Execute: " + command);
         Process process = new ProcessBuilder(command).start();
-        int exitCode = process.waitFor();
-        if (exitCode != 0) {
-            throw new CommandExecutionException(command, exitCode);
-        }
+        try {
             Scanner scanner = new Scanner(process.getInputStream());
             // read the versionCode of the installed package
             Pattern pattern = Pattern.compile("^    versionCode=(\\p{Digit}+).*");
@@ -371,6 +368,13 @@ public final class Main {
                     return !REQUIRED_APK_VERSION_CODE.equals(installedVersionCode);
                 }
             }
+        } finally {
+            int exitCode = process.waitFor();
+            if (exitCode != 0) {
+                // Overwrite any pending exception, the command just failed
+                throw new CommandExecutionException(command, exitCode);
+            }
+        }
         return true;
     }
 
```

Full diff:

```diff
diff --git a/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java b/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
index 03b6efc..7430560 100644
--- a/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
+++ b/relay-java/src/main/java/com/genymobile/gnirehtet/Main.java
@@ -357,18 +357,22 @@ public final class Main {
         List<String> command = createAdbCommand(serial, "shell", "dumpsys", "package", "com.genymobile.gnirehtet");
         Log.d(TAG, "Execute: " + command);
         Process process = new ProcessBuilder(command).start();
-        int exitCode = process.waitFor();
-        if (exitCode != 0) {
-            throw new CommandExecutionException(command, exitCode);
-        }
-        Scanner scanner = new Scanner(process.getInputStream());
-        // read the versionCode of the installed package
-        Pattern pattern = Pattern.compile("^    versionCode=(\\p{Digit}+).*");
-        while (scanner.hasNextLine()) {
-            Matcher matcher = pattern.matcher(scanner.nextLine());
-            if (matcher.matches()) {
-                String installedVersionCode = matcher.group(1);
-                return !REQUIRED_APK_VERSION_CODE.equals(installedVersionCode);
+        try {
+            Scanner scanner = new Scanner(process.getInputStream());
+            // read the versionCode of the installed package
+            Pattern pattern = Pattern.compile("^    versionCode=(\\p{Digit}+).*");
+            while (scanner.hasNextLine()) {
+                Matcher matcher = pattern.matcher(scanner.nextLine());
+                if (matcher.matches()) {
+                    String installedVersionCode = matcher.group(1);
+                    return !REQUIRED_APK_VERSION_CODE.equals(installedVersionCode);
+                }
+            }
+        } finally {
+            int exitCode = process.waitFor();
+            if (exitCode != 0) {
+                // Overwrite any pending exception, the command just failed
+                throw new CommandExecutionException(command, exitCode);
             }
         }
         return true;
```

**Comment by mythsman** [comment]
Oh, I tested it ,and you are right 👍  !

**Comment by rom1v** [comment]
Thank you :+1:

Fixed on `dev` branch: 9ad9bc83d1a6e6c2c3e095985269ab98f5ee08ab

I added you as a co-author of the commit, since you did the main part of the job, which is explaining the root cause: https://github.com/Genymobile/gnirehtet/issues/369#issuecomment-796796190

**Pull request closed without merging**
